# Generated by Django 4.1.7 on 2023-03-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='style',
            field=models.CharField(choices=[('friently', 'friently')], default='friently', max_length=100),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(choices=[('python', 'python')], default='python', max_length=100),
        ),
    ]
